apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}
  namespace:
  labels:
    appName: {{ .Values.name }}
specs:
  container:
    - name: {{ .Values.name }}
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/{{ .Values.name }}
      env:
        {{- toYaml .Values.env | indent 8 -}}
        